import Immutable from 'immutable';

import getBlog from 'daos/getBlog';
import getBlogContent from 'daos/getBlogContent'

const init = {
  blogs: [],
  folders: [],
  blogs_loaded: 0,
  blog_focus: {blog: undefined, loaded: 0, content: ""},
  transcript_map: {},
  env: "prod"  // client/index.jsx will dispatch SET_BLOG_ENVIRONMENT on init
}

const defaultState = Immutable.fromJS(init);

export default function blogsReducer(state = defaultState, action) {
  var nstate = state.toJS()
  switch(action.type) {
    case 'SET_BLOG_ENVIRONMENT':
      nstate.env = action.payload
      break
    case 'ADD_BLOG':
      // This event is generated by async loads and needs to kick off the content download on success
      var blog = action.payload.blog
      var dispatch = action.payload.dispatch
      var loaded = 1
      nstate.blog_focus = {blog, loaded}
      var env = nstate.env
      if (blog.rendered != undefined) {
        getBlogContent(dispatch, blog.rendered, env)
      } else if(blog != {}) {
        console.log("Got bad blog data:")
        console.log(blog)
      }
      break
    case 'SET_FOCUS_BLOG':
      var blog = action.payload.blog
      var fburi = ""
      if (nstate.blog_focus.blog != undefined) {
        fburi = nstate.blog_focus.blog.uri
      }
      if (blog.uri != fburi) {
        nstate.blog_focus.blog = blog
        nstate.blog_focus.loaded = 1
        nstate.blog_focus.content = ""
      }
      break
    case 'REQUEST_INJECT_BLOG':
      var i = 0
      nstate.blog_focus.loaded = 0        
      while (i < nstate.blogs.length) {
        var b = nstate.blogs[i]
        if (b.uri.indexOf('/episodes/') == -1 && b.uri.indexOf('/transcripts/') == -1) {
          nstate.blog_focus.blog = b
          nstate.blog_focus.loaded = 1
          nstate.blog_focus.content = ""
          var dispatch = action.payload.dispatch
          setTimeout(function() {
            getBlogContent(dispatch, b.rendered, env)
          },1)
          i = nstate.blogs.length
        }
        i += 1
      }
      break
    case 'INJECT_BLOG':
      // This event is generated to handle data that was prefetched and just needs to be injected
      var blog = action.payload.blog
      var loaded = 1
      nstate.blog_focus.blog = blog
      nstate.blog_focus.loaded = loaded
      break
    case 'ADD_BLOG_CONTENT':
      nstate.blog_focus.content = action.payload.content
      break
    case 'LOAD_BLOG':
      var dispatch = action.payload.dispatch
      var prettyname = action.payload.pathname
      var b = nstate.blog_focus.blog
      var pn = ""
      if (b != undefined) {
        pn = b.prettyname
      }
      if (b.blog_focus != undefined && b.blog_focus.content == undefined) {
        getBlog(dispatch, nstate.env, prettyname)
        nstate.blog_focus = {blog: undefined, loaded: 0, content: ""}
      }
      else if (b == undefined || prettyname != pn) {
        getBlog(dispatch, nstate.env, prettyname)
        nstate.blog_focus = {blog: undefined, loaded: 0, content: ""}
      }
      break
    case 'ADD_BLOGS':
  	  nstate.blogs = action.payload
      for (var i=0; i < nstate.blogs.length; i++) {
        var blog = nstate.blogs[i]
        if (blog.guid != undefined && blog.uri.indexOf('/transcripts/') != -1) {
          nstate.transcript_map[blog.guid] = blog
        }
      }
      break
    case 'SET_BLOGS_LOADED':
  	  nstate.blogs_loaded = action.payload
      break
    case 'FETCH_BLOGS_ERROR':
      nstate.blogs_loaded = -1
      nstate.blog_focus.loaded = -1
      break
    case 'SET_FOLDERS':
      nstate.folders = action.payload
      break
  }
  return Immutable.fromJS(nstate)
}

