import {
  INIT,
  INIT_SUCCESS,
  DESTROY,
  MESSAGE_SENT,
  MESSAGE_RECEIVED
} from '../client/reducer'

export { INIT, INIT_SUCCESS, DESTROY, MESSAGE_SENT, MESSAGE_RECEIVED }
export default [INIT, INIT_SUCCESS, DESTROY, MESSAGE_SENT, MESSAGE_RECEIVED]
