import React from 'react'
import { connect } from 'react-redux';

var countries = [
	{short: "us", long: "United States of America"},
	{short: "ca", long: "Canada"},
	{short: "uk", long: "United Kingdom"},
	{short: "au", long: "Australia"},
	{short: "fr", long: "France"},
	{short: "de", long: "Germany"},

{short: 'af', long: 'Afghanistan'},
{short: 'ax', long: 'Aland Islands'},
{short: 'al', long: 'Albania'},
{short: 'dz', long: 'Algeria'},
{short: 'as', long: 'American Samoa'},
{short: 'ad', long: 'Andorra'},
{short: 'ao', long: 'Angola'},
{short: 'ai', long: 'Anguilla'},
{short: 'aq', long: 'Antarctica'},
{short: 'ag', long: 'Antigua and Barbuda'},
{short: 'ar', long: 'Argentina'},
{short: 'am', long: 'Armenia'},
{short: 'aw', long: 'Aruba'},
{short: 'au', long: 'Australia'},
{short: 'at', long: 'Austria'},
{short: 'az', long: 'Azerbaijan'},
{short: 'bs', long: 'Bahamas'},
{short: 'bh', long: 'Bahrain'},
{short: 'bd', long: 'Bangladesh'},
{short: 'bb', long: 'Barbados'},
{short: 'by', long: 'Belarus'},
{short: 'be', long: 'Belgium'},
{short: 'bz', long: 'Belize'},
{short: 'bj', long: 'Benin'},
{short: 'bm', long: 'Bermuda'},
{short: 'bt', long: 'Bhutan'},
{short: 'bo', long: 'Bolivia'},
{short: 'ba', long: 'Bosnia and Herzegovina'},
{short: 'bw', long: 'Botswana'},
{short: 'bv', long: 'Bouvet Island'},
{short: 'br', long: 'Brazil'},
{short: 'vg', long: 'British Virgin Islands'},
{short: 'io', long: 'British Indian Ocean Territory'},
{short: 'bn', long: 'Brunei Darussalam'},
{short: 'bg', long: 'Bulgaria'},
{short: 'bf', long: 'Burkina Faso'},
{short: 'bi', long: 'Burundi'},
{short: 'kh', long: 'Cambodia'},
{short: 'cm', long: 'Cameroon'},
{short: 'ca', long: 'Canada'},
{short: 'cv', long: 'Cape Verde'},
{short: 'ky', long: 'Cayman Islands'},
{short: 'cf', long: 'Central African Republic'},
{short: 'td', long: 'Chad'},
{short: 'cl', long: 'Chile'},
{short: 'cn', long: 'China'},
{short: 'hk', long: 'Hong Kong, Special Administrative Region of China'},
{short: 'mo', long: 'Macao, Special Administrative Region of China'},
{short: 'cx', long: 'Christmas Island'},
{short: 'cc', long: 'Cocos (Keeling) Islands'},
{short: 'co', long: 'Colombia'},
{short: 'km', long: 'Comoros'},
{short: 'cg', long: 'Congo (Brazzaville)'},
{short: 'cd', long: 'Congo, Democratic Republic of the'},
{short: 'ck', long: 'Cook Islands'},
{short: 'cr', long: 'Costa Rica'},
{short: 'ci', long: 'Côte d\'Ivoire'},
{short: 'hr', long: 'Croatia'},
{short: 'cu', long: 'Cuba'},
{short: 'cy', long: 'Cyprus'},
{short: 'cz', long: 'Czech Republic'},
{short: 'dk', long: 'Denmark'},
{short: 'dj', long: 'Djibouti'},
{short: 'dm', long: 'Dominica'},
{short: 'do', long: 'Dominican Republic'},
{short: 'ec', long: 'Ecuador'},
{short: 'eg', long: 'Egypt'},
{short: 'sv', long: 'El Salvador'},
{short: 'gq', long: 'Equatorial Guinea'},
{short: 'er', long: 'Eritrea'},
{short: 'ee', long: 'Estonia'},
{short: 'et', long: 'Ethiopia'},
{short: 'fk', long: 'Falkland Islands (Malvinas)'},
{short: 'fo', long: 'Faroe Islands'},
{short: 'fj', long: 'Fiji'},
{short: 'fi', long: 'Finland'},
{short: 'fr', long: 'France'},
{short: 'gf', long: 'French Guiana'},
{short: 'pf', long: 'French Polynesia'},
{short: 'tf', long: 'French Southern Territories'},
{short: 'ga', long: 'Gabon'},
{short: 'gm', long: 'Gambia'},
{short: 'ge', long: 'Georgia'},
{short: 'de', long: 'Germany'},
{short: 'gh', long: 'Ghana'},
{short: 'gi', long: 'Gibraltar'},
{short: 'gr', long: 'Greece'},
{short: 'gl', long: 'Greenland'},
{short: 'gd', long: 'Grenada'},
{short: 'gp', long: 'Guadeloupe'},
{short: 'gu', long: 'Guam'},
{short: 'gt', long: 'Guatemala'},
{short: 'gg', long: 'Guernsey'},
{short: 'gn', long: 'Guinea'},
{short: 'gw', long: 'Guinea-Bissau'},
{short: 'gy', long: 'Guyana'},
{short: 'ht', long: 'Haiti'},
{short: 'hm', long: 'Heard Island and Mcdonald Islands'},
{short: 'va', long: 'Holy See (Vatican City State)'},
{short: 'hn', long: 'Honduras'},
{short: 'hu', long: 'Hungary'},
{short: 'is', long: 'Iceland'},
{short: 'in', long: 'India'},
{short: 'id', long: 'Indonesia'},
{short: 'ir', long: 'Iran, Islamic Republic of'},
{short: 'iq', long: 'Iraq'},
{short: 'ie', long: 'Ireland'},
{short: 'im', long: 'Isle of Man'},
{short: 'il', long: 'Israel'},
{short: 'it', long: 'Italy'},
{short: 'jm', long: 'Jamaica'},
{short: 'jp', long: 'Japan'},
{short: 'je', long: 'Jersey'},
{short: 'jo', long: 'Jordan'},
{short: 'kz', long: 'Kazakhstan'},
{short: 'ke', long: 'Kenya'},
{short: 'ki', long: 'Kiribati'},
{short: 'kp', long: 'Korea, Democratic People\'s Republic of'},
{short: 'kr', long: 'Korea, Republic of'},
{short: 'kw', long: 'Kuwait'},
{short: 'kg', long: 'Kyrgyzstan'},
{short: 'la', long: 'Lao PDR'},
{short: 'lv', long: 'Latvia'},
{short: 'lb', long: 'Lebanon'},
{short: 'ls', long: 'Lesotho'},
{short: 'lr', long: 'Liberia'},
{short: 'ly', long: 'Libya'},
{short: 'li', long: 'Liechtenstein'},
{short: 'lt', long: 'Lithuania'},
{short: 'lu', long: 'Luxembourg'},
{short: 'mk', long: 'Macedonia, Republic of'},
{short: 'mg', long: 'Madagascar'},
{short: 'mw', long: 'Malawi'},
{short: 'my', long: 'Malaysia'},
{short: 'mv', long: 'Maldives'},
{short: 'ml', long: 'Mali'},
{short: 'mt', long: 'Malta'},
{short: 'mh', long: 'Marshall Islands'},
{short: 'mq', long: 'Martinique'},
{short: 'mr', long: 'Mauritania'},
{short: 'mu', long: 'Mauritius'},
{short: 'yt', long: 'Mayotte'},
{short: 'mx', long: 'Mexico'},
{short: 'fm', long: 'Micronesia, Federated States of'},
{short: 'md', long: 'Moldova'},
{short: 'mc', long: 'Monaco'},
{short: 'mn', long: 'Mongolia'},
{short: 'me', long: 'Montenegro'},
{short: 'ms', long: 'Montserrat'},
{short: 'ma', long: 'Morocco'},
{short: 'mz', long: 'Mozambique'},
{short: 'mm', long: 'Myanmar'},
{short: 'na', long: 'Namibia'},
{short: 'nr', long: 'Nauru'},
{short: 'np', long: 'Nepal'},
{short: 'nl', long: 'Netherlands'},
{short: 'an', long: 'Netherlands Antilles'},
{short: 'nc', long: 'New Caledonia'},
{short: 'nz', long: 'New Zealand'},
{short: 'ni', long: 'Nicaragua'},
{short: 'ne', long: 'Niger'},
{short: 'ng', long: 'Nigeria'},
{short: 'nu', long: 'Niue'},
{short: 'nf', long: 'Norfolk Island'},
{short: 'mp', long: 'Northern Mariana Islands'},
{short: 'no', long: 'Norway'},
{short: 'om', long: 'Oman'},
{short: 'pk', long: 'Pakistan'},
{short: 'pw', long: 'Palau'},
{short: 'ps', long: 'Palestinian Territory, Occupied'},
{short: 'pa', long: 'Panama'},
{short: 'pg', long: 'Papua New Guinea'},
{short: 'py', long: 'Paraguay'},
{short: 'pe', long: 'Peru'},
{short: 'ph', long: 'Philippines'},
{short: 'pn', long: 'Pitcairn'},
{short: 'pl', long: 'Poland'},
{short: 'pt', long: 'Portugal'},
{short: 'pr', long: 'Puerto Rico'},
{short: 'qa', long: 'Qatar'},
{short: 're', long: 'Réunion'},
{short: 'ro', long: 'Romania'},
{short: 'ru', long: 'Russian Federation'},
{short: 'rw', long: 'Rwanda'},
{short: 'bl', long: 'Saint-Barthélemy'},
{short: 'sh', long: 'Saint Helena'},
{short: 'kn', long: 'Saint Kitts and Nevis'},
{short: 'lc', long: 'Saint Lucia'},
{short: 'mf', long: 'Saint-Martin (French part)'},
{short: 'pm', long: 'Saint Pierre and Miquelon'},
{short: 'vc', long: 'Saint Vincent and Grenadines'},
{short: 'ws', long: 'Samoa'},
{short: 'sm', long: 'San Marino'},
{short: 'st', long: 'Sao Tome and Principe'},
{short: 'sa', long: 'Saudi Arabia'},
{short: 'sn', long: 'Senegal'},
{short: 'rs', long: 'Serbia'},
{short: 'sc', long: 'Seychelles'},
{short: 'sl', long: 'Sierra Leone'},
{short: 'sg', long: 'Singapore'},
{short: 'sk', long: 'Slovakia'},
{short: 'si', long: 'Slovenia'},
{short: 'sb', long: 'Solomon Islands'},
{short: 'so', long: 'Somalia'},
{short: 'za', long: 'South Africa'},
{short: 'gs', long: 'South Georgia and the South Sandwich Islands'},
{short: 'ss', long: 'South Sudan'},
{short: 'es', long: 'Spain'},
{short: 'lk', long: 'Sri Lanka'},
{short: 'sd', long: 'Sudan'},
{short: 'sr', long: 'Suriname *'},
{short: 'sj', long: 'Svalbard and Jan Mayen Islands'},
{short: 'sz', long: 'Swaziland'},
{short: 'se', long: 'Sweden'},
{short: 'ch', long: 'Switzerland'},
{short: 'sy', long: 'Syrian Arab Republic (Syria)'},
{short: 'tw', long: 'Taiwan, Republic of China'},
{short: 'tj', long: 'Tajikistan'},
{short: 'tz', long: 'Tanzania *, United Republic of'},
{short: 'th', long: 'Thailand'},
{short: 'tl', long: 'Timor-Leste'},
{short: 'tg', long: 'Togo'},
{short: 'tk', long: 'Tokelau'},
{short: 'to', long: 'Tonga'},
{short: 'tt', long: 'Trinidad and Tobago'},
{short: 'tn', long: 'Tunisia'},
{short: 'tr', long: 'Turkey'},
{short: 'tm', long: 'Turkmenistan'},
{short: 'tc', long: 'Turks and Caicos Islands'},
{short: 'tv', long: 'Tuvalu'},
{short: 'ug', long: 'Uganda'},
{short: 'ua', long: 'Ukraine'},
{short: 'ae', long: 'United Arab Emirates'},
{short: 'gb', long: 'United Kingdom'},
{short: 'us', long: 'United States of America'},
{short: 'um', long: 'United States Minor Outlying Islands'},
{short: 'uy', long: 'Uruguay'},
{short: 'uz', long: 'Uzbekistan'},
{short: 'vu', long: 'Vanuatu'},
{short: 've', long: 'Venezuela (Bolivarian Republic of)'},
{short: 'vn', long: 'Viet Nam'},
{short: 'vi', long: 'Virgin Islands, US'},
{short: 'wf', long: 'Wallis and Futuna Islands'},
{short: 'eh', long: 'Western Sahara'},
{short: 'ye', long: 'Yemen'},
{short: 'zm', long: 'Zambia'},
{short: 'zw', long: 'Zimbabwe'}
]

class CountrySelector extends React.Component {
	
	onChange(e) {
		var val = e.target.value
		var short = val
		var long = ""
		for (var i=0; i < countries.length; i++) {
			var country = countries[i]
			if (country.short == short) {
				long = country.long
			}
		}
		this.props.dispatch({type: "CHANGE_COUNTRY", payload: {short, long} })
	}

	render() {
		var ocart = this.props.cart.toJS()
		var short = ocart.country_short
		return (
			<div className="country-selector">
				<select className="country" onChange={this.onChange.bind(this)} value={short}>
					{countries.map(function(country) {
						return (
							<option key={country.short} value={country.short}>{country.long}</option>
						)
					})}
				</select>
			</div>
		)
	}
}

export default connect(state => ({ cart: state.cart }))(CountrySelector)

